services:
    postgresdb:
        image: postgres:16.4
        container_name: net-vault-postgres-db
        restart: no
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "12345"
        ports:
            - "5432:5432"
        expose:
            - "5432"
        networks:
            - primary
        volumes:
            - "./.volumes/postgresql:/var/lib/postgresql/data"

    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        container_name: net-vault-node-api
        env_file:
            - .env
        environment:
            - PORT=3001
        ports:
            - "3001:3001"
        command: bash -c "npm run prisma:generate && npm run start:dev"
        networks:
            - primary
        volumes:
            - ./src:/home/node/app/src
            - $HOME/.aws/credentials:/root/.aws/credentials:ro
            - $HOME/.aws/config:/root/.aws/config:ro

    worker:
        build:
            context: .
            dockerfile: worker.Dockerfile
            target: base
        container_name: net-vault-worker
        command: bash -c "npm run prisma:generate && npm run start:worker:dev"
        env_file:
            - .env
        depends_on:
            - redis
        networks:
            - primary
        volumes:
            - ./src:/home/node/app/src
            - $HOME/.aws/credentials:/root/.aws/credentials:ro
            - $HOME/.aws/config:/root/.aws/config:ro

    redis:
        image: redis:7.2
        container_name: net-vault-redis
        restart: "no"
        ports:
            - "6379:6379"
        command: ["redis-server", "--appendonly", "yes"]
        networks:
            - primary
        volumes:
            - ./.volumes/redis:/data

networks:
    primary:
        driver: bridge
